require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MappingsController do

  # This should return the minimal set of attributes required to create a valid
  # Mapping. As you add validations to Mapping, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all mappings as @mappings" do
      mapping = Mapping.create! valid_attributes
      get :index
      assigns(:mappings).should eq([mapping])
    end
  end

  describe "GET show" do
    it "assigns the requested mapping as @mapping" do
      mapping = Mapping.create! valid_attributes
      get :show, :id => mapping.id.to_s
      assigns(:mapping).should eq(mapping)
    end
  end

  describe "GET new" do
    it "assigns a new mapping as @mapping" do
      get :new
      assigns(:mapping).should be_a_new(Mapping)
    end
  end

  describe "GET edit" do
    it "assigns the requested mapping as @mapping" do
      mapping = Mapping.create! valid_attributes
      get :edit, :id => mapping.id.to_s
      assigns(:mapping).should eq(mapping)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Mapping" do
        expect {
          post :create, :mapping => valid_attributes
        }.to change(Mapping, :count).by(1)
      end

      it "assigns a newly created mapping as @mapping" do
        post :create, :mapping => valid_attributes
        assigns(:mapping).should be_a(Mapping)
        assigns(:mapping).should be_persisted
      end

      it "redirects to the created mapping" do
        post :create, :mapping => valid_attributes
        response.should redirect_to(Mapping.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mapping as @mapping" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mapping.any_instance.stub(:save).and_return(false)
        post :create, :mapping => {}
        assigns(:mapping).should be_a_new(Mapping)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mapping.any_instance.stub(:save).and_return(false)
        post :create, :mapping => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mapping" do
        mapping = Mapping.create! valid_attributes
        # Assuming there are no other mappings in the database, this
        # specifies that the Mapping created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Mapping.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => mapping.id, :mapping => {'these' => 'params'}
      end

      it "assigns the requested mapping as @mapping" do
        mapping = Mapping.create! valid_attributes
        put :update, :id => mapping.id, :mapping => valid_attributes
        assigns(:mapping).should eq(mapping)
      end

      it "redirects to the mapping" do
        mapping = Mapping.create! valid_attributes
        put :update, :id => mapping.id, :mapping => valid_attributes
        response.should redirect_to(mapping)
      end
    end

    describe "with invalid params" do
      it "assigns the mapping as @mapping" do
        mapping = Mapping.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mapping.any_instance.stub(:save).and_return(false)
        put :update, :id => mapping.id.to_s, :mapping => {}
        assigns(:mapping).should eq(mapping)
      end

      it "re-renders the 'edit' template" do
        mapping = Mapping.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mapping.any_instance.stub(:save).and_return(false)
        put :update, :id => mapping.id.to_s, :mapping => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mapping" do
      mapping = Mapping.create! valid_attributes
      expect {
        delete :destroy, :id => mapping.id.to_s
      }.to change(Mapping, :count).by(-1)
    end

    it "redirects to the mappings list" do
      mapping = Mapping.create! valid_attributes
      delete :destroy, :id => mapping.id.to_s
      response.should redirect_to(mappings_url)
    end
  end

end
