require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NominationsController do

  # This should return the minimal set of attributes required to create a valid
  # Nomination. As you add validations to Nomination, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all nominations as @nominations" do
      nomination = Nomination.create! valid_attributes
      get :index
      assigns(:nominations).should eq([nomination])
    end
  end

  describe "GET show" do
    it "assigns the requested nomination as @nomination" do
      nomination = Nomination.create! valid_attributes
      get :show, :id => nomination.id.to_s
      assigns(:nomination).should eq(nomination)
    end
  end

  describe "GET new" do
    it "assigns a new nomination as @nomination" do
      get :new
      assigns(:nomination).should be_a_new(Nomination)
    end
  end

  describe "GET edit" do
    it "assigns the requested nomination as @nomination" do
      nomination = Nomination.create! valid_attributes
      get :edit, :id => nomination.id.to_s
      assigns(:nomination).should eq(nomination)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Nomination" do
        expect {
          post :create, :nomination => valid_attributes
        }.to change(Nomination, :count).by(1)
      end

      it "assigns a newly created nomination as @nomination" do
        post :create, :nomination => valid_attributes
        assigns(:nomination).should be_a(Nomination)
        assigns(:nomination).should be_persisted
      end

      it "redirects to the created nomination" do
        post :create, :nomination => valid_attributes
        response.should redirect_to(Nomination.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved nomination as @nomination" do
        # Trigger the behavior that occurs when invalid params are submitted
        Nomination.any_instance.stub(:save).and_return(false)
        post :create, :nomination => {}
        assigns(:nomination).should be_a_new(Nomination)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Nomination.any_instance.stub(:save).and_return(false)
        post :create, :nomination => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested nomination" do
        nomination = Nomination.create! valid_attributes
        # Assuming there are no other nominations in the database, this
        # specifies that the Nomination created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Nomination.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => nomination.id, :nomination => {'these' => 'params'}
      end

      it "assigns the requested nomination as @nomination" do
        nomination = Nomination.create! valid_attributes
        put :update, :id => nomination.id, :nomination => valid_attributes
        assigns(:nomination).should eq(nomination)
      end

      it "redirects to the nomination" do
        nomination = Nomination.create! valid_attributes
        put :update, :id => nomination.id, :nomination => valid_attributes
        response.should redirect_to(nomination)
      end
    end

    describe "with invalid params" do
      it "assigns the nomination as @nomination" do
        nomination = Nomination.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Nomination.any_instance.stub(:save).and_return(false)
        put :update, :id => nomination.id.to_s, :nomination => {}
        assigns(:nomination).should eq(nomination)
      end

      it "re-renders the 'edit' template" do
        nomination = Nomination.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Nomination.any_instance.stub(:save).and_return(false)
        put :update, :id => nomination.id.to_s, :nomination => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested nomination" do
      nomination = Nomination.create! valid_attributes
      expect {
        delete :destroy, :id => nomination.id.to_s
      }.to change(Nomination, :count).by(-1)
    end

    it "redirects to the nominations list" do
      nomination = Nomination.create! valid_attributes
      delete :destroy, :id => nomination.id.to_s
      response.should redirect_to(nominations_url)
    end
  end

end
