require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OpinionsController do

  # This should return the minimal set of attributes required to create a valid
  # Opinion. As you add validations to Opinion, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all opinions as @opinions" do
      opinion = Opinion.create! valid_attributes
      get :index
      assigns(:opinions).should eq([opinion])
    end
  end

  describe "GET show" do
    it "assigns the requested opinion as @opinion" do
      opinion = Opinion.create! valid_attributes
      get :show, :id => opinion.id.to_s
      assigns(:opinion).should eq(opinion)
    end
  end

  describe "GET new" do
    it "assigns a new opinion as @opinion" do
      get :new
      assigns(:opinion).should be_a_new(Opinion)
    end
  end

  describe "GET edit" do
    it "assigns the requested opinion as @opinion" do
      opinion = Opinion.create! valid_attributes
      get :edit, :id => opinion.id.to_s
      assigns(:opinion).should eq(opinion)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Opinion" do
        expect {
          post :create, :opinion => valid_attributes
        }.to change(Opinion, :count).by(1)
      end

      it "assigns a newly created opinion as @opinion" do
        post :create, :opinion => valid_attributes
        assigns(:opinion).should be_a(Opinion)
        assigns(:opinion).should be_persisted
      end

      it "redirects to the created opinion" do
        post :create, :opinion => valid_attributes
        response.should redirect_to(Opinion.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved opinion as @opinion" do
        # Trigger the behavior that occurs when invalid params are submitted
        Opinion.any_instance.stub(:save).and_return(false)
        post :create, :opinion => {}
        assigns(:opinion).should be_a_new(Opinion)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Opinion.any_instance.stub(:save).and_return(false)
        post :create, :opinion => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested opinion" do
        opinion = Opinion.create! valid_attributes
        # Assuming there are no other opinions in the database, this
        # specifies that the Opinion created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Opinion.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => opinion.id, :opinion => {'these' => 'params'}
      end

      it "assigns the requested opinion as @opinion" do
        opinion = Opinion.create! valid_attributes
        put :update, :id => opinion.id, :opinion => valid_attributes
        assigns(:opinion).should eq(opinion)
      end

      it "redirects to the opinion" do
        opinion = Opinion.create! valid_attributes
        put :update, :id => opinion.id, :opinion => valid_attributes
        response.should redirect_to(opinion)
      end
    end

    describe "with invalid params" do
      it "assigns the opinion as @opinion" do
        opinion = Opinion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Opinion.any_instance.stub(:save).and_return(false)
        put :update, :id => opinion.id.to_s, :opinion => {}
        assigns(:opinion).should eq(opinion)
      end

      it "re-renders the 'edit' template" do
        opinion = Opinion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Opinion.any_instance.stub(:save).and_return(false)
        put :update, :id => opinion.id.to_s, :opinion => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested opinion" do
      opinion = Opinion.create! valid_attributes
      expect {
        delete :destroy, :id => opinion.id.to_s
      }.to change(Opinion, :count).by(-1)
    end

    it "redirects to the opinions list" do
      opinion = Opinion.create! valid_attributes
      delete :destroy, :id => opinion.id.to_s
      response.should redirect_to(opinions_url)
    end
  end

end
